---
title: "CuentasPolíticos"
author: "Federico Acosta y Lara"
date: "7/11/2021"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Librerias
```{r}
library(dplyr)
library(stopwords)
library(kableExtra)
library(ggplot2)
library(patchwork)
```

Importación de datos
```{r}
Oficiales <- rio::import(here::here("Data", "Raw data", "hashtagoficiales.csv"))
Cuentas <- rio::import(here::here("Data", "Funcionarios_cuentas.csv"))

```


Conteo de tweets por partido y cargo
```{r}
Conteo <- Oficiales %>%
        select(screenName) %>% 
        inner_join(Cuentas, by=c("screenName" = "Cuenta")) %>% 
        group_by(Cargo, Partido) %>% 
        count(Partido)
```

Armado de tablas
```{r}
Diputados <- as.data.frame(Conteo[Conteo$Cargo=="Diputado",])
Diputados <- rbind(Diputados, c("Diputado", "CA", "0"), c("Diputado", "Otro", "0"))
Diputados$Partido <- factor(Diputados$Partido, levels = c("FA", "PN", "PC", "CA", "Otro"))
Diputados$n <- as.numeric(Diputados$n)


Senadores <- as.data.frame(Conteo[Conteo$Cargo=="Senador",])
Senadores <- rbind(Senadores, c("Senador", "PC", "0"), c("Senador", "CA", "0"))
Senadores$Partido <- factor(Senadores$Partido, levels = c("FA", "PN", "PC", "CA"))
Senadores$n <- as.numeric(Senadores$n)


Ministros <- as.data.frame(Conteo[Conteo$Cargo=="Ministro",])
Ministros <- rbind(Ministros, c("Ministro", "CA", "0"))
Ministros$Partido <- factor(Ministros$Partido, levels = c("PN", "PC", "CA","PI"))
Ministros$n <- as.numeric(Ministros$n)

```


Gráficos - Funcionarios

```{r, include=FALSE}

DipGraf <- ggplot(Diputados, aes(x=Partido, y=n)) + 
                geom_col(fill = c("chocolate1", "brown2", 
                                  "cornflowerblue", "darkgoldenrod1", "darkgray")) +
                ggtitle("Diputados") +
                xlab("Partido") + ylab("") +
                ylim(0,300) +
                geom_text(aes(label = n), size = 4, hjust = 0, vjust = 0) +
                theme_minimal()

SenGraf <- ggplot(Senadores, aes(x=Partido, y=n)) + 
                geom_col(fill = c("chocolate1", "cornflowerblue", 
                                  "brown2", "darkgoldenrod1")) +
                ggtitle("Senadores") +
                xlab("Partido") + ylab("") +
                ylim(0,40) +
                geom_text(aes(label = n), size = 4, hjust = 0, vjust = 0) +
                theme_minimal()

MinGraf <- ggplot(Ministros, aes(x=Partido, y=n)) + 
                geom_col(fill = c("brown2", "darkmagenta", 
                                  "cornflowerblue", "darkgoldenrod1")) +
                ggtitle("Ministros") +
                xlab("Partido") + ylab("") +
                ylim(0,8) +
                geom_text(aes(label = n), size = 4, hjust = 0, vjust = 0) +
                theme_minimal()



jpeg(filename = "Figures/Final figures/TweetsFuncionarios.jpg", 
     width = 3200, height = 1800, res = 300)

DipGraf + (SenGraf / MinGraf)

dev.off()
```

Partidos políticos (Cuentas institucionales)
```{r}
C_Institucionales <- as.data.frame(rbind(FA="Frente_Amplio", PN="PNACIONAL", PC="PartidoColorado", CA="Cabildo_UY", PI="pindependiente", PG="lagenteuy", PE="pEcologistaUy"))
names(C_Institucionales) <- c("Cuenta")

ConteoP <- Oficiales %>%
        select(screenName) %>% 
        inner_join(C_Institucionales, by=c("screenName" = "Cuenta")) %>%
        count(screenName)

Partidos <- as.data.frame(ConteoP)
Partidos <- rbind(Partidos, c("Cabildo_UY", "0"), c("lagenteuy", "0"), c("pEcologistaUy", "0"))
names(Partidos) <- c("Cuenta", "n")
Partidos$Cuenta <- factor(Partidos$Cuenta, levels = c("Frente_Amplio", "PNACIONAL", "PartidoColorado", "Cabildo_UY", "pindependiente", "lagenteuy", "pEcologistaUy"))
Partidos$n <- as.numeric(Partidos$n)

```

Gráficos - Partidos políticos
```{r}
PartGraf <- ggplot(Partidos, aes(x=Cuenta, y=n)) + 
                geom_col(fill = c("chocolate1", "brown2", 
                                  "darkmagenta", "cornflowerblue", "azure4", "azure4", "azure4")) +
                ggtitle("Cuentas institucionales") +
                xlab("") + ylab("") +
                ylim(0,40) +
                geom_text(aes(label = n), size = 4, hjust = 0.5, vjust = 0.5, family="Times") +
                theme_minimal() +
                theme(text=element_text(size=12, family="Times"))

jpeg(filename = "Figures/Final figures/TweetsPartidos.jpg", 
     width = 3200, height = 1800, res = 300)

PartGraf

dev.off()
```


Medios de comunicación

```{r}
#Prensa escrita
PrensaE <- c("elpaisuy", "ObservadorUY", "ladiaria", "larepublica_uy", "BUSQUEDAonline")
PrensaE <- as.data.frame(PrensaE)
names(PrensaE) <- "Cuenta"

ConteoE <- Oficiales %>%
        select(screenName) %>% 
        inner_join(PrensaE, by=c("screenName" = "Cuenta")) %>%
        count(screenName)

PrensaE <- rbind(ConteoE, c("ObservadorUY", 0), c("BUSQUEDAonline", 0))
PrensaE$n <- as.numeric(PrensaE$n)
# Informativos televisivos
Informativos <- c("TelemundoUY", "Subrayado", "TelenocheUy", "InfoTNU", "infocapitaluy")
Informativos <- as.data.frame(Informativos)
names(Informativos) <- "Cuenta"

ConteoI <- Oficiales %>%
        select(screenName) %>% 
        inner_join(Informativos, by=c("screenName" = "Cuenta")) %>%
        count(screenName)

Informativos <- rbind(ConteoI, c("Subrayado", 0), c("TelenocheUy", 0), c("InfoTNU", 0))
Informativos$n <- as.numeric(Informativos$n)
```


Ploteo - Medios de comunicación

```{r, include=FALSE}
MediosGrafPE <- ggplot(PrensaE, aes(stats::reorder(x=screenName, X=-n), y=n)) + 
                geom_col(fill = c(wesanderson::wes_palette("BottleRocket2", type = "discrete"))) +
                ggtitle("Prensa escrita") +
                xlab("") + ylab("") +
                ylim(0,40) +
                geom_text(aes(label = n), size = 4, hjust = 0.5, vjust = 0.5, family="Times") +
                theme_minimal() +
                theme(text=element_text(size=12, family="Times"))

MediosGrafTV <- ggplot(Informativos, aes(stats::reorder(x=screenName, X=-n), y=n)) + 
                geom_col(fill = c(wesanderson::wes_palette("BottleRocket2", type = "discrete"))) +
                ggtitle("Informativos - TV") +
                xlab("") + ylab("") +
                ylim(0,8) +
                geom_text(aes(label = n), size = 4, hjust = 0.5, vjust = 0.5, family="Times") +
                theme_minimal() +
                theme(text=element_text(size=12, family="Times"))


jpeg(filename = "Figures/Final figures/TweetsMedios.jpg", 
     width = 3200, height = 1800, res = 300)

MediosGrafPE / MediosGrafTV

dev.off()

```





Funcionarios - Porcentuales 

```{r, include=FALSE}
Conteo2 <- Oficiales %>%
        select(screenName) %>% 
        inner_join(Cuentas, by=c("screenName" = "Cuenta")) %>% 
        group_by(Cargo, Partido, Nombre) %>% 
        distinct()
Conteo2 <- as.data.frame(Conteo2)
Conteo2 <- Conteo2 %>% count(Cargo, Partido)


DiputadosConf <- cbind(c("FA", "PN", "PC", "CA", "PI", "PG", "PE"), c(39, 29, 12, 9, 1, 1, 1))
DiputadosConf <-as.data.frame(DiputadosConf)
names(DiputadosConf) <- c("Partido", "n")
DiputadosConf$n <- as.numeric(as.character(DiputadosConf$n))


SenadoresConf <- cbind(c("FA", "PN", "PC", "CA"), as.numeric(c(8, 9, 4, 2)))
SenadoresConf <-as.data.frame(SenadoresConf)
names(SenadoresConf) <- c("Partido", "n")
SenadoresConf$n <- as.numeric(as.character(SenadoresConf$n))


MinistrosConf <- cbind(c("PN", "PC", "CA", "PI"), as.numeric(c(7, 3, 2, 1)))
MinistrosConf <-as.data.frame(MinistrosConf)
names(MinistrosConf) <- c("Partido", "n")
MinistrosConf$n <- as.numeric(as.character(MinistrosConf$n))



ConteoD <- Conteo2[Conteo2$Cargo=="Diputado",]
ConteoS <- Conteo2[Conteo2$Cargo=="Senador",]
ConteoM <- Conteo2[Conteo2$Cargo=="Ministro",]

Dip <- DiputadosConf %>% left_join(ConteoD, by=c("Partido")) %>% 
            select(Partido, n.x, n.y) %>%
            replace(is.na(.), 0) %>% 
            mutate(prop=round(100*(n.y/n.x),0))

Dip$Partido <- factor(Dip$Partido, levels = c("FA", "PN", "PC", "CA","PI", "PG", "PE"))


Sen <- SenadoresConf %>% left_join(ConteoS, by=c("Partido")) %>% 
            select(Partido, n.x, n.y) %>%
            replace(is.na(.), 0) %>% 
            mutate(prop=round(100*(n.y/n.x),0))

Sen$Partido <- factor(Sen$Partido, levels = c("FA", "PN", "PC", "CA","PI", "PG", "PE"))


Min <- MinistrosConf %>% left_join(ConteoM, by=c("Partido")) %>% 
            select(Partido, n.x, n.y) %>%
            replace(is.na(.), 0) %>% 
            mutate(prop=round(100*(n.y/n.x),0))

Min$Partido <- factor(Min$Partido, levels = c("PN", "PC", "CA","PI"))

```


Gráficos Funcionarios - Porcentuales

```{r, include=FALSE}
DipGraf <- ggplot(Dip, aes(x=Partido, y=prop)) + 
                geom_col(fill = c("chocolate1", "cornflowerblue", "brown2", "darkgoldenrod1", 
                                  "darkgray", "darkgray", "darkgray")) +
                ggtitle("Diputados") +
                xlab("Partido") + ylab("%") +
                ylim(0,100) +
                geom_text(aes(label = prop), size = 3.5, hjust = 0.5, vjust = 0.5,, family="Times") +
                theme_minimal() +
                theme(text=element_text(size=12, family="Times"))

SenGraf <- ggplot(Sen, aes(x=Partido, y=prop)) + 
                geom_col(fill = c("chocolate1", "cornflowerblue", 
                                  "brown2", "darkgoldenrod1")) +
                ggtitle("Senadores") +
                xlab("Partido") + ylab("%") +
                ylim(0,100) +
                geom_text(aes(label = prop), size = 3.5, hjust = 0.5, vjust = 0.5, family="Times") +
                theme_minimal() +
                theme(text=element_text(size=12, family="Times"))

MinGraf <- ggplot(Min, aes(x=Partido, y=prop)) + 
                geom_col(fill = c("cornflowerblue","brown2","darkgoldenrod1", "darkmagenta")) +
                ggtitle("Ministros") +
                xlab("Partido") + ylab("%") +
                ylim(0,100) +
                geom_text(aes(label = prop), size = 3.2, hjust = 0.5, vjust = 0.5, family="Times") +
                theme_minimal() +
                theme(text=element_text(size=12, family="Times"))

```

```{r, include=FALSE}

jpeg(filename = "Figures/Final figures/TweetsFuncionarios.jpg", 
     width = 3200, height = 1800, res = 300)

DipGraf + (SenGraf / MinGraf)

dev.off()
```


